# Generated by Django 3.1.6 on 2021-02-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('ed', models.TextField()),
                ('bcc', models.TextField()),
                ('eos', models.TextField()),
                ('tron', models.TextField()),
                ('ic', models.TextField()),
            ],
        ),
    ]
